import type { LunarHolidayDef, SolarHolidayDef } from './types';

/**
 * Official and cultural holidays fixed on the solar (Jalali) calendar. These recur on
 * the same Jalali date every year and are exact.
 */
export const SOLAR_HOLIDAYS: SolarHolidayDef[] = [
  { month: 1, day: 1, title: 'عید نوروز', titleEn: 'Nowruz', type: 'national', official: true },
  { month: 1, day: 2, title: 'عید نوروز', titleEn: 'Nowruz', type: 'national', official: true },
  { month: 1, day: 3, title: 'عید نوروز', titleEn: 'Nowruz', type: 'national', official: true },
  { month: 1, day: 4, title: 'عید نوروز', titleEn: 'Nowruz', type: 'national', official: true },
  {
    month: 1,
    day: 12,
    title: 'روز جمهوری اسلامی',
    titleEn: 'Islamic Republic Day',
    type: 'national',
    official: true,
  },
  {
    month: 1,
    day: 13,
    title: 'روز طبیعت (سیزده‌به‌در)',
    titleEn: 'Nature Day (Sizdah Bedar)',
    type: 'national',
    official: true,
  },
  {
    month: 3,
    day: 14,
    title: 'رحلت امام خمینی',
    titleEn: 'Demise of Imam Khomeini',
    type: 'national',
    official: true,
  },
  {
    month: 3,
    day: 15,
    title: 'قیام ۱۵ خرداد',
    titleEn: 'Uprising of 15 Khordad',
    type: 'national',
    official: true,
  },
  {
    month: 11,
    day: 22,
    title: 'پیروزی انقلاب اسلامی',
    titleEn: 'Victory of the Islamic Revolution',
    type: 'national',
    official: true,
  },
  {
    month: 12,
    day: 29,
    title: 'روز ملی شدن صنعت نفت',
    titleEn: 'Nationalization of the Oil Industry',
    type: 'national',
    official: true,
  },
  // Cultural observances (not public days off).
  {
    month: 9,
    day: 30,
    title: 'شب یلدا',
    titleEn: 'Yalda Night',
    type: 'cultural',
    official: false,
  },
];

/**
 * Religious holidays anchored to the Hijri (lunar) calendar. Dates are recomputed per
 * year from the tabular calendar and flagged `approximate`.
 */
export const LUNAR_HOLIDAYS: LunarHolidayDef[] = [
  {
    hijriMonth: 1,
    hijriDay: 9,
    title: 'تاسوعای حسینی',
    titleEn: 'Tasua',
    type: 'religious',
    official: true,
  },
  {
    hijriMonth: 1,
    hijriDay: 10,
    title: 'عاشورای حسینی',
    titleEn: 'Ashura',
    type: 'religious',
    official: true,
  },
  {
    hijriMonth: 2,
    hijriDay: 20,
    title: 'اربعین حسینی',
    titleEn: 'Arbaeen',
    type: 'religious',
    official: true,
  },
  {
    hijriMonth: 2,
    hijriDay: 28,
    title: 'رحلت پیامبر و شهادت امام حسن',
    titleEn: 'Demise of the Prophet & Martyrdom of Imam Hasan',
    type: 'religious',
    official: true,
  },
  {
    hijriMonth: 2,
    hijriDay: 30,
    title: 'شهادت امام رضا',
    titleEn: 'Martyrdom of Imam Reza',
    type: 'religious',
    official: true,
  },
  {
    hijriMonth: 3,
    hijriDay: 8,
    title: 'شهادت امام حسن عسکری',
    titleEn: 'Martyrdom of Imam Hasan al-Askari',
    type: 'religious',
    official: true,
  },
  {
    hijriMonth: 3,
    hijriDay: 17,
    title: 'میلاد پیامبر و امام صادق',
    titleEn: 'Birth of the Prophet & Imam Sadiq',
    type: 'religious',
    official: true,
  },
  {
    hijriMonth: 6,
    hijriDay: 3,
    title: 'شهادت حضرت فاطمه',
    titleEn: 'Martyrdom of Fatimah',
    type: 'religious',
    official: true,
  },
  {
    hijriMonth: 7,
    hijriDay: 13,
    title: 'ولادت امام علی',
    titleEn: 'Birth of Imam Ali',
    type: 'religious',
    official: true,
  },
  {
    hijriMonth: 7,
    hijriDay: 27,
    title: 'مبعث',
    titleEn: "Prophet's Mission (Mab'ath)",
    type: 'religious',
    official: true,
  },
  {
    hijriMonth: 8,
    hijriDay: 15,
    title: 'ولادت امام زمان',
    titleEn: 'Birth of Imam Mahdi',
    type: 'religious',
    official: true,
  },
  {
    hijriMonth: 9,
    hijriDay: 21,
    title: 'شهادت امام علی',
    titleEn: 'Martyrdom of Imam Ali',
    type: 'religious',
    official: true,
  },
  {
    hijriMonth: 10,
    hijriDay: 1,
    title: 'عید فطر',
    titleEn: 'Eid al-Fitr',
    type: 'religious',
    official: true,
  },
  {
    hijriMonth: 10,
    hijriDay: 2,
    title: 'تعطیل عید فطر',
    titleEn: 'Eid al-Fitr Holiday',
    type: 'religious',
    official: true,
  },
  {
    hijriMonth: 10,
    hijriDay: 25,
    title: 'شهادت امام صادق',
    titleEn: 'Martyrdom of Imam Sadiq',
    type: 'religious',
    official: true,
  },
  {
    hijriMonth: 12,
    hijriDay: 10,
    title: 'عید قربان',
    titleEn: 'Eid al-Adha',
    type: 'religious',
    official: true,
  },
  {
    hijriMonth: 12,
    hijriDay: 18,
    title: 'عید غدیر خم',
    titleEn: 'Eid al-Ghadir',
    type: 'religious',
    official: true,
  },
];
