// Emits each demo component's source into a normal .ts module (src/generated-sources.ts),
// keyed by "<group>/<name>". The Angular (Analog) Vite plugin claims every .ts file and
// strips Vite's `?raw` query, so importing source text at build time isn't reliable — a
// generated map sidesteps that. Runs as `prebuild`.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const demosDir = join(here, '..', 'src', 'demos');
const sources = {};

function walk(dir) {
  for (const name of readdirSync(dir).sort()) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p);
    else if (name.endsWith('.component.ts')) {
      const key = relative(demosDir, p).replace(/\.component\.ts$/, '').replaceAll('\\', '/');
      sources[key] = readFileSync(p, 'utf8');
    }
  }
}
walk(demosDir);

const body =
  `// AUTO-GENERATED by scripts/gen-sources.mjs — do not edit by hand.\n` +
  `export const SOURCES: Record<string, string> = ${JSON.stringify(sources, null, 2)};\n`;
writeFileSync(join(here, '..', 'src', 'generated-sources.ts'), body);
console.log(`gen-sources: wrote ${Object.keys(sources).length} demo sources`);
